print('Verdadeiro ou Falso para Palavras!')
palavra = input('Digite algo para saber as informações: ')
print('qual o tipo?')
print(type(palavra))
print('Ele é numérico?')
print(palavra.isalnum())
print('Ele é Alfa numérico?')
print(palavra.isalpha())
print('Está tudo em Minusculo?')
print(palavra.islower())
print('Está tudo Maiusculo?')
print(palavra.isupper())